New-NetFirewallRule -Program “c:\Program Files\Common Files\Autodesk Shared\CLM\V5\MSVC14\cliccore\acwebbrowser.exe” -Action Block -Profile Domain, Private -DisplayName “ACAD Banner” -Description “fcku adsk” -Direction Outbound
New-NetFirewallRule -Program “c:\Program Files\Common Files\Autodesk Shared\CLM\V6\MSVC14\cliccore\acwebbrowser.exe” -Action Block -Profile Domain, Private -DisplayName “ACAD Banner” -Description “fcku adsk” -Direction Outbound
New-NetFirewallRule -Program “c:\Program Files\Common Files\Autodesk Shared\CLM\V7\MSVC14\cliccore\acwebbrowser.exe” -Action Block -Profile Domain, Private -DisplayName “ACAD Banner” -Description “fcku adsk” -Direction Outbound
New-NetFirewallRule -Program “c:\Program Files\Autodesk\AutoCAD LT 2019\AcWebBrowser\AcWebBrowser.exe” -Action Block -Profile Domain, Private -DisplayName “ACAD Banner” -Description “fcku adsk” -Direction Outbound
New-NetFirewallRule -Program “c:\Program Files\Autodesk\AutoCAD 2024\AcCef\AcCefSubprocess.exe" -Action Block -Profile Domain, Private -DisplayName “ACAD Banner” -Description “fcku adsk” -Direction Outbound
New-NetFirewallRule -Program “c:\Program Files\Autodesk\AutoCAD 2023\AcCef\AcCefSubprocess.exe" -Action Block -Profile Domain, Private -DisplayName “ACAD Banner” -Description “fcku adsk” -Direction Outbound
New-NetFirewallRule -Program "C:\Program Files\Autodesk\AutoCAD 2022\AcCef\AcCefSubprocess.exe" -Action Block -Profile Domain, Private -DisplayName “ACAD Banner” -Description “fcku adsk” -Direction Outbound
New-NetFirewallRule -Program “c:\Program Files\Autodesk\AutoCAD 2021\AcWebBrowser\AcWebBrowser.exe” -Action Block -Profile Domain, Private -DisplayName “ACAD Banner” -Description “fcku adsk” -Direction Outbound
New-NetFirewallRule -Program “c:\Program Files\Autodesk\AutoCAD 2020\AcWebBrowser\AcWebBrowser.exe” -Action Block -Profile Domain, Private -DisplayName “ACAD Banner” -Description “fcku adsk” -Direction Outbound
New-NetFirewallRule -Program “c:\Program Files\Autodesk\AutoCAD 2019\AcWebBrowser\AcWebBrowser.exe” -Action Block -Profile Domain, Private -DisplayName “ACAD Banner” -Description “fcku adsk” -Direction Outbound
New-NetFirewallRule -Program “c:\Program Files\Autodesk\AutoCAD 2018\AcWebBrowser\AcWebBrowser.exe” -Action Block -Profile Domain, Private -DisplayName “ACAD Banner” -Description “fcku adsk” -Direction Outbound
New-NetFirewallRule -Program “c:\Program Files\Autodesk\AutoCAD 2017\AcWebBrowser\AcWebBrowser.exe” -Action Block -Profile Domain, Private -DisplayName “ACAD Banner” -Description “fcku adsk” -Direction Outbound
New-NetFirewallRule -Program “c:\Program Files\Autodesk\AutoCAD 2016\AcWebBrowser\AcWebBrowser.exe” -Action Block -Profile Domain, Private -DisplayName “ACAD Banner” -Description “fcku adsk” -Direction Outbound
